In [10]:
#Extração via API

# import sys
# sys.path.append("..")

# from extract.api import coletar_dados
# import pandas as pd

# # resultado = buscar_preco(59, 5585, "2011-3")
# resultado = coletar_dados()
# df = pd.DataFrame(resultado)
# df

In [11]:
#Extração via API

import sys
sys.path.append("..")

from extract.dados_fipe import dados_fipe
import pandas as pd

df = pd.DataFrame(dados_fipe)
df

,TipoVeiculo,Valor,Marca,Modelo,AnoModelo,Combustivel,CodigoFipe,MesReferencia,SiglaCombustivel
0,1,"R$ 36.471,93",VW - VolksWagen,GOL 2.0 4x2,2017,Flex,000001-3,julho de 2026,F
1,1,"R$ 113.569,99",VW - VolksWagen,GOL 1.0 4x2 Aut.,2021,Eletrico,000002-9,março de 2026,E
2,1,"R$ 107.097,59",VW - VolksWagen,GOL 2.0 4x2,2014,Gasolina,000003-5,março de 2026,G
3,1,"R$ 293.807,50",VW - VolksWagen,GOL 1.0,2026,Diesel,000004-9,maio de 2026,D
4,1,"R$ 78.089,50",VW - VolksWagen,POLO 2.0 Aut.,2016,Diesel,000005-2,março de 2026,D
...,...,...,...,...,...,...,...,...,...
195,1,"R$ 95.407,14",Nissan,MARCH 1.5 4x4 Aut.,2010,Flex,000196-5,dezembro de 2026,F
196,1,"R$ 215.725,96",Nissan,SENTRA 1.8 4x2,2018,Eletrico,000197-4,agosto de 2026,E
197,1,"R$ 187.154,27",Nissan,SENTRA 4.0 4x4,2017,Eletrico,000198-4,agosto de 2026,E
198,1,"R$ 100.147,64",Nissan,SENTRA 4.0 4x2,2022,Flex,000199-0,fevereiro de 2026,F
199,1,"R$ 260.625,14",Nissan,SENTRA 1.6 4x2,2012,Gasolina,000200-8,outubro de 2026,G

In [12]:
def limpar_valor(valor_str):
    valor = valor_str.replace("R$ ", "")
    valor = valor.replace(".", "")
    valor = valor.replace(",", ".")
    return float(valor)

df["Valor"] = df["Valor"].apply(limpar_valor)
df

,TipoVeiculo,Valor,Marca,Modelo,AnoModelo,Combustivel,CodigoFipe,MesReferencia,SiglaCombustivel
0,1,36471.93,VW - VolksWagen,GOL 2.0 4x2,2017,Flex,000001-3,julho de 2026,F
1,1,113569.99,VW - VolksWagen,GOL 1.0 4x2 Aut.,2021,Eletrico,000002-9,março de 2026,E
2,1,107097.59,VW - VolksWagen,GOL 2.0 4x2,2014,Gasolina,000003-5,março de 2026,G
3,1,293807.50,VW - VolksWagen,GOL 1.0,2026,Diesel,000004-9,maio de 2026,D
4,1,78089.50,VW - VolksWagen,POLO 2.0 Aut.,2016,Diesel,000005-2,março de 2026,D
...,...,...,...,...,...,...,...,...,...
195,1,95407.14,Nissan,MARCH 1.5 4x4 Aut.,2010,Flex,000196-5,dezembro de 2026,F
196,1,215725.96,Nissan,SENTRA 1.8 4x2,2018,Eletrico,000197-4,agosto de 2026,E
197,1,187154.27,Nissan,SENTRA 4.0 4x4,2017,Eletrico,000198-4,agosto de 2026,E
198,1,100147.64,Nissan,SENTRA 4.0 4x2,2022,Flex,000199-0,fevereiro de 2026,F
199,1,260625.14,Nissan,SENTRA 1.6 4x2,2012,Gasolina,000200-8,outubro de 2026,G

In [13]:
def limpar_marca(marca_str):
    partes = marca_str.split(" - ")
    if len(partes) == 2:
        return {
            "prefixo": partes[0].strip(),
            "marca":   partes[1].strip()
        }
    else:

        return {
            "prefixo": None,
            "marca":   partes[0].strip()
        }


marca_expandida = df["Marca"].apply(limpar_marca).apply(pd.Series)
df["prefixo"] = marca_expandida["prefixo"]
df["marca"]   = marca_expandida["marca"]
df = df.drop(columns=["Marca"])
df

,TipoVeiculo,Valor,Modelo,AnoModelo,Combustivel,CodigoFipe,MesReferencia,SiglaCombustivel,prefixo,marca
0,1,36471.93,GOL 2.0 4x2,2017,Flex,000001-3,julho de 2026,F,VW,VolksWagen
1,1,113569.99,GOL 1.0 4x2 Aut.,2021,Eletrico,000002-9,março de 2026,E,VW,VolksWagen
2,1,107097.59,GOL 2.0 4x2,2014,Gasolina,000003-5,março de 2026,G,VW,VolksWagen
3,1,293807.50,GOL 1.0,2026,Diesel,000004-9,maio de 2026,D,VW,VolksWagen
4,1,78089.50,POLO 2.0 Aut.,2016,Diesel,000005-2,março de 2026,D,VW,VolksWagen
...,...,...,...,...,...,...,...,...,...,...
195,1,95407.14,MARCH 1.5 4x4 Aut.,2010,Flex,000196-5,dezembro de 2026,F,None,Nissan
196,1,215725.96,SENTRA 1.8 4x2,2018,Eletrico,000197-4,agosto de 2026,E,None,Nissan
197,1,187154.27,SENTRA 4.0 4x4,2017,Eletrico,000198-4,agosto de 2026,E,None,Nissan
198,1,100147.64,SENTRA 4.0 4x2,2022,Flex,000199-0,fevereiro de 2026,F,None,Nissan
199,1,260625.14,SENTRA 1.6 4x2,2012,Gasolina,000200-8,outubro de 2026,G,None,Nissan

In [14]:
def limpar_data(mes_ref_str):
    partes = mes_ref_str.split()
    return {
        "mes_nome": partes[0].strip(),
        "ano_referencia": int(partes[2].strip())
    }


data_limpar = df["MesReferencia"].apply(limpar_data).apply(pd.Series)
df["mes_nome"] = data_limpar["mes_nome"]
df["ano_referencia"] = data_limpar["ano_referencia"]
df = df.drop(columns=["MesReferencia"])
df

,TipoVeiculo,Valor,Modelo,AnoModelo,Combustivel,CodigoFipe,SiglaCombustivel,prefixo,marca,mes_nome,ano_referencia
0,1,36471.93,GOL 2.0 4x2,2017,Flex,000001-3,F,VW,VolksWagen,julho,2026
1,1,113569.99,GOL 1.0 4x2 Aut.,2021,Eletrico,000002-9,E,VW,VolksWagen,março,2026
2,1,107097.59,GOL 2.0 4x2,2014,Gasolina,000003-5,G,VW,VolksWagen,março,2026
3,1,293807.50,GOL 1.0,2026,Diesel,000004-9,D,VW,VolksWagen,maio,2026
4,1,78089.50,POLO 2.0 Aut.,2016,Diesel,000005-2,D,VW,VolksWagen,março,2026
...,...,...,...,...,...,...,...,...,...,...,...
195,1,95407.14,MARCH 1.5 4x4 Aut.,2010,Flex,000196-5,F,None,Nissan,dezembro,2026
196,1,215725.96,SENTRA 1.8 4x2,2018,Eletrico,000197-4,E,None,Nissan,agosto,2026
197,1,187154.27,SENTRA 4.0 4x4,2017,Eletrico,000198-4,E,None,Nissan,agosto,2026
198,1,100147.64,SENTRA 4.0 4x2,2022,Flex,000199-0,F,None,Nissan,fevereiro,2026
199,1,260625.14,SENTRA 1.6 4x2,2012,Gasolina,000200-8,G,None,Nissan,outubro,2026

In [15]:
def extrair_modelo(modelo_str):
    partes = modelo_str.split()
    return partes[0]

df["modelo"] = df["Modelo"].apply(extrair_modelo)
df

,TipoVeiculo,Valor,Modelo,AnoModelo,Combustivel,CodigoFipe,SiglaCombustivel,prefixo,marca,mes_nome,ano_referencia,modelo
0,1,36471.93,GOL 2.0 4x2,2017,Flex,000001-3,F,VW,VolksWagen,julho,2026,GOL
1,1,113569.99,GOL 1.0 4x2 Aut.,2021,Eletrico,000002-9,E,VW,VolksWagen,março,2026,GOL
2,1,107097.59,GOL 2.0 4x2,2014,Gasolina,000003-5,G,VW,VolksWagen,março,2026,GOL
3,1,293807.50,GOL 1.0,2026,Diesel,000004-9,D,VW,VolksWagen,maio,2026,GOL
4,1,78089.50,POLO 2.0 Aut.,2016,Diesel,000005-2,D,VW,VolksWagen,março,2026,POLO
...,...,...,...,...,...,...,...,...,...,...,...,...
195,1,95407.14,MARCH 1.5 4x4 Aut.,2010,Flex,000196-5,F,None,Nissan,dezembro,2026,MARCH
196,1,215725.96,SENTRA 1.8 4x2,2018,Eletrico,000197-4,E,None,Nissan,agosto,2026,SENTRA
197,1,187154.27,SENTRA 4.0 4x4,2017,Eletrico,000198-4,E,None,Nissan,agosto,2026,SENTRA
198,1,100147.64,SENTRA 4.0 4x2,2022,Flex,000199-0,F,None,Nissan,fevereiro,2026,SENTRA
199,1,260625.14,SENTRA 1.6 4x2,2012,Gasolina,000200-8,G,None,Nissan,outubro,2026,SENTRA

In [16]:
import re 
def extrair_tracao(tracao_str):
    resultado = re.search(r"4x\d", tracao_str)
    if resultado:
        return resultado.group()
    return None

df["Tracao"] = df["Modelo"].apply(extrair_tracao)
df

,TipoVeiculo,Valor,Modelo,AnoModelo,Combustivel,CodigoFipe,SiglaCombustivel,prefixo,marca,mes_nome,ano_referencia,modelo,Tracao
0,1,36471.93,GOL 2.0 4x2,2017,Flex,000001-3,F,VW,VolksWagen,julho,2026,GOL,4x2
1,1,113569.99,GOL 1.0 4x2 Aut.,2021,Eletrico,000002-9,E,VW,VolksWagen,março,2026,GOL,4x2
2,1,107097.59,GOL 2.0 4x2,2014,Gasolina,000003-5,G,VW,VolksWagen,março,2026,GOL,4x2
3,1,293807.50,GOL 1.0,2026,Diesel,000004-9,D,VW,VolksWagen,maio,2026,GOL,None
4,1,78089.50,POLO 2.0 Aut.,2016,Diesel,000005-2,D,VW,VolksWagen,março,2026,POLO,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1,95407.14,MARCH 1.5 4x4 Aut.,2010,Flex,000196-5,F,None,Nissan,dezembro,2026,MARCH,4x4
196,1,215725.96,SENTRA 1.8 4x2,2018,Eletrico,000197-4,E,None,Nissan,agosto,2026,SENTRA,4x2
197,1,187154.27,SENTRA 4.0 4x4,2017,Eletrico,000198-4,E,None,Nissan,agosto,2026,SENTRA,4x4
198,1,100147.64,SENTRA 4.0 4x2,2022,Flex,000199-0,F,None,Nissan,fevereiro,2026,SENTRA,4x2
199,1,260625.14,SENTRA 1.6 4x2,2012,Gasolina,000200-8,G,None,Nissan,outubro,2026,SENTRA,4x2

In [17]:
def extrair_cambio(cambio_str):
    if re.search(r"Aut", cambio_str):
        return "Automatico"
    return "Manual"

df["cambio"] = df["Modelo"].apply(extrair_cambio)
df

,TipoVeiculo,Valor,Modelo,AnoModelo,Combustivel,CodigoFipe,SiglaCombustivel,prefixo,marca,mes_nome,ano_referencia,modelo,Tracao,cambio
0,1,36471.93,GOL 2.0 4x2,2017,Flex,000001-3,F,VW,VolksWagen,julho,2026,GOL,4x2,Manual
1,1,113569.99,GOL 1.0 4x2 Aut.,2021,Eletrico,000002-9,E,VW,VolksWagen,março,2026,GOL,4x2,Automatico
2,1,107097.59,GOL 2.0 4x2,2014,Gasolina,000003-5,G,VW,VolksWagen,março,2026,GOL,4x2,Manual
3,1,293807.50,GOL 1.0,2026,Diesel,000004-9,D,VW,VolksWagen,maio,2026,GOL,None,Manual
4,1,78089.50,POLO 2.0 Aut.,2016,Diesel,000005-2,D,VW,VolksWagen,março,2026,POLO,None,Automatico
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1,95407.14,MARCH 1.5 4x4 Aut.,2010,Flex,000196-5,F,None,Nissan,dezembro,2026,MARCH,4x4,Automatico
196,1,215725.96,SENTRA 1.8 4x2,2018,Eletrico,000197-4,E,None,Nissan,agosto,2026,SENTRA,4x2,Manual
197,1,187154.27,SENTRA 4.0 4x4,2017,Eletrico,000198-4,E,None,Nissan,agosto,2026,SENTRA,4x4,Manual
198,1,100147.64,SENTRA 4.0 4x2,2022,Flex,000199-0,F,None,Nissan,fevereiro,2026,SENTRA,4x2,Manual
199,1,260625.14,SENTRA 1.6 4x2,2012,Gasolina,000200-8,G,None,Nissan,outubro,2026,SENTRA,4x2,Manual

In [18]:
def extrair_cilidrada(cilindrada_str):
    resultado = re.search(r"\d+\.\d+",cilindrada_str)
    if resultado:
        return resultado.group()
    return None

df["cilindrada"] = df["Modelo"].apply(extrair_cilidrada)
df = df.drop(columns=["Modelo"])
df

,TipoVeiculo,Valor,AnoModelo,Combustivel,CodigoFipe,SiglaCombustivel,prefixo,marca,mes_nome,ano_referencia,modelo,Tracao,cambio,cilindrada
0,1,36471.93,2017,Flex,000001-3,F,VW,VolksWagen,julho,2026,GOL,4x2,Manual,2.0
1,1,113569.99,2021,Eletrico,000002-9,E,VW,VolksWagen,março,2026,GOL,4x2,Automatico,1.0
2,1,107097.59,2014,Gasolina,000003-5,G,VW,VolksWagen,março,2026,GOL,4x2,Manual,2.0
3,1,293807.50,2026,Diesel,000004-9,D,VW,VolksWagen,maio,2026,GOL,None,Manual,1.0
4,1,78089.50,2016,Diesel,000005-2,D,VW,VolksWagen,março,2026,POLO,None,Automatico,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1,95407.14,2010,Flex,000196-5,F,None,Nissan,dezembro,2026,MARCH,4x4,Automatico,1.5
196,1,215725.96,2018,Eletrico,000197-4,E,None,Nissan,agosto,2026,SENTRA,4x2,Manual,1.8
197,1,187154.27,2017,Eletrico,000198-4,E,None,Nissan,agosto,2026,SENTRA,4x4,Manual,4.0
198,1,100147.64,2022,Flex,000199-0,F,None,Nissan,fevereiro,2026,SENTRA,4x2,Manual,4.0
199,1,260625.14,2012,Gasolina,000200-8,G,None,Nissan,outubro,2026,SENTRA,4x2,Manual,1.6

In [19]:
def mapear_tipo(tipo):
    mapa = {1: "carro", 2:"moto",3:"caminhão"}
    return mapa.get(tipo,"desconhecido")

df["TipoVeiculo"] = df["TipoVeiculo"].apply(mapear_tipo)
df = df.drop(columns=["SiglaCombustivel"])
df

,TipoVeiculo,Valor,AnoModelo,Combustivel,CodigoFipe,prefixo,marca,mes_nome,ano_referencia,modelo,Tracao,cambio,cilindrada
0,carro,36471.93,2017,Flex,000001-3,VW,VolksWagen,julho,2026,GOL,4x2,Manual,2.0
1,carro,113569.99,2021,Eletrico,000002-9,VW,VolksWagen,março,2026,GOL,4x2,Automatico,1.0
2,carro,107097.59,2014,Gasolina,000003-5,VW,VolksWagen,março,2026,GOL,4x2,Manual,2.0
3,carro,293807.50,2026,Diesel,000004-9,VW,VolksWagen,maio,2026,GOL,None,Manual,1.0
4,carro,78089.50,2016,Diesel,000005-2,VW,VolksWagen,março,2026,POLO,None,Automatico,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,carro,95407.14,2010,Flex,000196-5,None,Nissan,dezembro,2026,MARCH,4x4,Automatico,1.5
196,carro,215725.96,2018,Eletrico,000197-4,None,Nissan,agosto,2026,SENTRA,4x2,Manual,1.8
197,carro,187154.27,2017,Eletrico,000198-4,None,Nissan,agosto,2026,SENTRA,4x4,Manual,4.0
198,carro,100147.64,2022,Flex,000199-0,None,Nissan,fevereiro,2026,SENTRA,4x2,Manual,4.0
199,carro,260625.14,2012,Gasolina,000200-8,None,Nissan,outubro,2026,SENTRA,4x2,Manual,1.6

In [20]:
def renomear_colunas(df):
    df = df.rename(columns={
        "TipoVeiculo": "tipo_veiculo",
        "AnoModelo":   "ano_modelo",
        "CodigoFipe":  "codigo_fipe",
        "Tracao":      "tracao",
        "Valor":       "valor",
        "Combustivel": "combustivel"
    })
    df = df[[
        "codigo_fipe", "tipo_veiculo", "modelo", "marca",
        "valor", "prefixo", "ano_modelo", "tracao",
        "cambio", "cilindrada", "combustivel", "ano_referencia"
    ]]
    return df

df = renomear_colunas(df)
df

,codigo_fipe,tipo_veiculo,modelo,marca,valor,prefixo,ano_modelo,tracao,cambio,cilindrada,combustivel,ano_referencia
0,000001-3,carro,GOL,VolksWagen,36471.93,VW,2017,4x2,Manual,2.0,Flex,2026
1,000002-9,carro,GOL,VolksWagen,113569.99,VW,2021,4x2,Automatico,1.0,Eletrico,2026
2,000003-5,carro,GOL,VolksWagen,107097.59,VW,2014,4x2,Manual,2.0,Gasolina,2026
3,000004-9,carro,GOL,VolksWagen,293807.50,VW,2026,None,Manual,1.0,Diesel,2026
4,000005-2,carro,POLO,VolksWagen,78089.50,VW,2016,None,Automatico,2.0,Diesel,2026
...,...,...,...,...,...,...,...,...,...,...,...,...
195,000196-5,carro,MARCH,Nissan,95407.14,None,2010,4x4,Automatico,1.5,Flex,2026
196,000197-4,carro,SENTRA,Nissan,215725.96,None,2018,4x2,Manual,1.8,Eletrico,2026
197,000198-4,carro,SENTRA,Nissan,187154.27,None,2017,4x4,Manual,4.0,Eletrico,2026
198,000199-0,carro,SENTRA,Nissan,100147.64,None,2022,4x2,Manual,4.0,Flex,2026
199,000200-8,carro,SENTRA,Nissan,260625.14,None,2012,4x2,Manual,1.6,Gasolina,2026

In [26]:
df_marca = df[["prefixo","marca"]].drop_duplicates().reset_index(drop=True)
df_marca["id_marca"] = df_marca.index + 1

df_modelo = df[["codigo_fipe", "modelo", "tipo_veiculo",
                "cilindrada", "tracao", "cambio", "combustivel", "marca"]].drop_duplicates()

df_modelo = df_modelo.merge(df_marca[["id_marca","marca"]], on="marca")
df_modelo = df_modelo.drop(columns=["marca"])
df_modelo["id_modelo"] = df_modelo.index + 1

df_preco = df[["codigo_fipe","valor","ano_referencia","ano_modelo"]]
df_preco = df_preco.merge(df_modelo[["id_modelo","codigo_fipe"]], on="codigo_fipe")
df_preco = df_preco.drop(columns=["codigo_fipe"])

df_marca

  prefixo       marca  id_marca
0      VW  VolksWagen         1
1    FIAT        Fiat         2
2      GM   Chevrolet         3
3    None      Toyota         4
4    None       Honda         5
5    None     Hyundai         6
6    None     Renault         7
7    None        Ford         8
8    None        Jeep         9
9    None      Nissan        10