In [66]:
import sys
sys.path.append("..")

from extract.api import buscar_preco
import pandas as pd

resultado = buscar_preco(59, 5585, "2011-3")
df = pd.DataFrame([resultado])
df

,TipoVeiculo,Valor,Marca,Modelo,AnoModelo,Combustivel,CodigoFipe,MesReferencia,SiglaCombustivel
0,1,"R$ 62.099,00",VW - VolksWagen,AMAROK CD2.0 16V/S CD2.0 16V TDI 4x2 Die,2011,Diesel,005329-5,julho de 2026,D

In [67]:
def limpar_valor(valor_str):
    valor = valor_str.replace("R$ ", "")
    valor = valor.replace(".", "")
    valor = valor.replace(",", ".")
    return float(valor)

df["Valor"] = df["Valor"].apply(limpar_valor)
df

,TipoVeiculo,Valor,Marca,Modelo,AnoModelo,Combustivel,CodigoFipe,MesReferencia,SiglaCombustivel
0,1,62099.0,VW - VolksWagen,AMAROK CD2.0 16V/S CD2.0 16V TDI 4x2 Die,2011,Diesel,005329-5,julho de 2026,D

In [68]:
def limpar_marca(marca_str):
    partes = marca_str.split(" - ")
    return {
        "prefixo": partes[0].strip(),
        "marca":   partes[1].strip()
    }

# expande em duas colunas
marca_expandida = df["Marca"].apply(limpar_marca).apply(pd.Series)
df["prefixo"] = marca_expandida["prefixo"]
df["marca"]   = marca_expandida["marca"]
df = df.drop(columns=["Marca"])
df

,TipoVeiculo,Valor,Modelo,AnoModelo,Combustivel,CodigoFipe,MesReferencia,SiglaCombustivel,prefixo,marca
0,1,62099.0,AMAROK CD2.0 16V/S CD2.0 16V TDI 4x2 Die,2011,Diesel,005329-5,julho de 2026,D,VW,VolksWagen

In [69]:
def limpar_data(mes_ref_str):
    partes = mes_ref_str.split()
    return {
        "mes_nome": partes[0].strip(),
        "ano_referencia": int(partes[2].strip())
    }


data_limpar = df["MesReferencia"].apply(limpar_data).apply(pd.Series)
df["mes_nome"] = data_limpar["mes_nome"]
df["ano_referencia"] = data_limpar["ano_referencia"]
df = df.drop(columns=["MesReferencia"])
df

,TipoVeiculo,Valor,Modelo,AnoModelo,Combustivel,CodigoFipe,SiglaCombustivel,prefixo,marca,mes_nome,ano_referencia
0,1,62099.0,AMAROK CD2.0 16V/S CD2.0 16V TDI 4x2 Die,2011,Diesel,005329-5,D,VW,VolksWagen,julho,2026

In [70]:
def extrair_modelo(modelo_str):
    partes = modelo_str.split()
    return partes[0]

df["modelo"] = df["Modelo"].apply(extrair_modelo)
df

,TipoVeiculo,Valor,Modelo,AnoModelo,Combustivel,CodigoFipe,SiglaCombustivel,prefixo,marca,mes_nome,ano_referencia,modelo
0,1,62099.0,AMAROK CD2.0 16V/S CD2.0 16V TDI 4x2 Die,2011,Diesel,005329-5,D,VW,VolksWagen,julho,2026,AMAROK

In [ ]:
import re 
def extrair_tracao(tracao_str):
    resultado = re.search(r"4x\d", tracao_str)
    if resultado:
        return resultado.group()
    return None

df["Tracao"] = df["Modelo"].apply(extrair_tracao)
df

,TipoVeiculo,Valor,Modelo,AnoModelo,Combustivel,CodigoFipe,SiglaCombustivel,prefixo,marca,mes_nome,ano_referencia,modelo,Tacao
0,1,62099.0,AMAROK CD2.0 16V/S CD2.0 16V TDI 4x2 Die,2011,Diesel,005329-5,D,VW,VolksWagen,julho,2026,AMAROK,4x2