In [22]:
import subprocess
subprocess.run(["pip", "install", "psycopg2-binary", "sqlalchemy"], check=True)
print("Instalado!")

Requirement already satisfied: psycopg2-binary in /opt/conda/lib/python3.11/site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in /opt/conda/lib/python3.11/site-packages (2.0.22)
Requirement already satisfied: typing-extensions>=4.2.0 in /opt/conda/lib/python3.11/site-packages (from sqlalchemy) (4.8.0)
Requirement already satisfied: greenlet!=0.4.17 in /opt/conda/lib/python3.11/site-packages (from sqlalchemy) (3.0.0)
Instalado!

In [1]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://postgres:postgres@postgres:5432/fipe")

dim_marca  = pd.read_sql("SELECT * FROM dim_marca",  engine)
dim_modelo = pd.read_sql("SELECT * FROM dim_modelo", engine)
fato_preco = pd.read_sql("SELECT * FROM fato_preco", engine)

print("dim_marca: ",  dim_marca.shape)
print("dim_modelo:",  dim_modelo.shape)
print("fato_preco:",  fato_preco.shape)

dim_marca:  (10, 3)
dim_modelo: (200, 9)
fato_preco: (200, 6)

In [57]:
print(dim_marca.columns)
print(dim_modelo.columns)
print(fato_preco.columns)

Index(['id_marca', 'prefixo', 'marca'], dtype='object')
Index(['id_modelo', 'id_marca', 'codigo_fipe', 'modelo', 'tipo_veiculo',
       'cilindrada', 'tracao', 'cambio', 'combustivel'],
      dtype='object')
Index(['id_preco', 'id_modelo', 'ano_modelo', 'valor', 'mes_nome',
       'ano_referencia'],
      dtype='object')

In [3]:
query_sql1 = pd.read_sql("""
    SELECT
        m.marca AS marca_veiculo,
        ROUND(AVG(p.valor)::numeric, 2)  AS media_valor
    FROM fato_preco AS p
    JOIN dim_modelo AS md ON p.id_modelo = md.id_modelo
    JOIN dim_marca  AS m  ON md.id_marca = m.id_marca
    GROUP BY m.marca
    ORDER BY media_valor DESC
""", engine)

print(query_sql1)

  marca_veiculo  media_valor
0       Renault    233366.60
1     Chevrolet    219938.95
2       Hyundai    214196.83
3          Fiat    190235.08
4          Ford    185414.28
5         Honda    183629.72
6          Jeep    177366.10
7        Nissan    174848.28
8        Toyota    170455.29
9    VolksWagen    166316.17

In [10]:
df = fato_preco.merge(dim_modelo, on="id_modelo") \
            .merge(dim_marca,on="id_marca")
resultado = df.groupby("marca")["valor"]\
               .mean()\
               .reset_index()\
               .rename(columns={"valor":"media_valor"})\
               .sort_values("media_valor",ascending=False)
resultado["media_valor"] = resultado["media_valor"].round(2)
resultado

        marca  media_valor
7     Renault    233366.60
0   Chevrolet    219938.95
4     Hyundai    214196.83
1        Fiat    190235.08
2        Ford    185414.28
3       Honda    183629.72
5        Jeep    177366.10
6      Nissan    174848.28
8      Toyota    170455.29
9  VolksWagen    166316.17

In [4]:
query_2 = pd.read_sql("""
    SELECT
        m.marca,
        md.modelo,
        md.combustivel,
        p.ano_modelo,
        p.valor
    FROM fato_preco AS p
    JOIN dim_modelo AS md ON p.id_modelo = md.id_modelo
    JOIN dim_marca  AS m  ON md.id_marca = m.id_marca
    ORDER BY p.valor DESC
    LIMIT 5
""", engine)

print(query_2)

        marca   modelo combustivel  ano_modelo      valor
0     Renault   DUSTER    Gasolina        2024  349484.86
1      Nissan    MARCH    Eletrico        2022  349020.52
2      Toyota     RAV4      Diesel        2020  347409.88
3     Renault  SANDERO    Gasolina        2018  344592.18
4  VolksWagen  SAVEIRO        Flex        2015  344525.24

In [12]:
df = fato_preco.merge(dim_modelo, on='id_modelo') \
               .merge(dim_marca, on='id_marca')

resultado = df[['marca', 'modelo', 'combustivel', 'ano_modelo', 'valor']] \
              .sort_values('valor', ascending=False) \
              .head(5)

resultado

          marca   modelo combustivel  ano_modelo      valor
130     Renault   DUSTER    Gasolina        2024  349484.86
194      Nissan    MARCH    Eletrico        2022  349020.52
77       Toyota     RAV4      Diesel        2020  347409.88
124     Renault  SANDERO    Gasolina        2018  344592.18
18   VolksWagen  SAVEIRO        Flex        2015  344525.24

In [5]:
# "Quais os 5 modelos mais baratos do banco, mostrando marca, modelo, combustível, ano e valor?""Quais os 5 modelos mais baratos do banco, mostrando marca, modelo, combustível, ano e valor?"

query_3 = pd.read_sql("""
    SELECT
        m.marca       AS marca_veiculo,
        md.modelo     AS modelo_veiculo,
        md.combustivel,
        fp.ano_modelo AS ano_veiculo,
        fp.valor      AS valor_veiculo
    FROM fato_preco AS fp
    JOIN dim_modelo AS md ON fp.id_modelo = md.id_modelo
    JOIN dim_marca  AS m  ON md.id_marca  = m.id_marca
    ORDER BY fp.valor ASC
    LIMIT 5
""", engine)

print(query_3)

  marca_veiculo modelo_veiculo combustivel  ano_veiculo  valor_veiculo
0    VolksWagen         VOYAGE      Diesel         2023       26395.12
1        Toyota          YARIS      Diesel         2021       27578.35
2         Honda           HR-V    Eletrico         2019       28417.10
3          Fiat          PULSE      Diesel         2017       30318.83
4     Chevrolet          CRUZE    Eletrico         2023       31924.64

In [8]:
df = fato_preco.merge(dim_modelo, on="id_modelo")\
               .merge(dim_marca,on="id_marca")
resultado = df[["marca","modelo","combustivel","ano_modelo","valor"]].sort_values("valor",ascending=True).reset_index().head(5)

resultado

   index       marca  modelo combustivel  ano_modelo     valor
0     12  VolksWagen  VOYAGE      Diesel        2023  26395.12
1     69      Toyota   YARIS      Diesel        2021  27578.35
2     87       Honda    HR-V    Eletrico        2019  28417.10
3     36        Fiat   PULSE      Diesel        2017  30318.83
4     56   Chevrolet   CRUZE    Eletrico        2023  31924.64

In [7]:
# "Qual o total de veículos por tipo (carro, moto, caminhao)?"
query_4 = pd.read_sql("""
    SELECT
        tipo_veiculo,
        COUNT(*) AS total
    FROM dim_modelo
    GROUP BY tipo_veiculo
    ORDER BY total DESC
""", engine)

print(query_4)

  tipo_veiculo  total
0        carro    200

In [14]:
resultado = dim_modelo.groupby("tipo_veiculo")["id_modelo"] \
                      .count() \
                      .reset_index() \
                      .rename(columns={"id_modelo": "total"}) \
                      .sort_values("total", ascending=False)

resultado

  tipo_veiculo  total
0        carro    200

In [20]:
query_5 = pd.read_sql("""
    SELECT
        m.marca,
        MAX(fv.valor)                    AS preco_maximo,
        MIN(fv.valor)                    AS preco_minimo,
        MAX(fv.valor) - MIN(fv.valor)    AS variacao_preco
    FROM fato_preco AS fv
    JOIN dim_modelo AS md ON fv.id_modelo = md.id_modelo
    JOIN dim_marca  AS m  ON md.id_marca  = m.id_marca
    GROUP BY m.marca
    ORDER BY variacao_preco DESC
""", engine)

print(query_5)

        marca  preco_maximo  preco_minimo  variacao_preco
0      Toyota     347409.88      27578.35       319831.53
1  VolksWagen     344525.24      26395.12       318130.12
2      Nissan     349020.52      34249.65       314770.87
3   Chevrolet     342560.76      31924.64       310636.12
4     Renault     349484.86      42517.13       306967.73
5        Jeep     335047.31      33258.56       301788.75
6        Fiat     330378.80      30318.83       300059.97
7     Hyundai     341650.14      46771.90       294878.24
8       Honda     321893.04      28417.10       293475.94
9        Ford     314488.89      60851.24       253637.65

In [22]:
df = fato_preco.merge(dim_modelo, on="id_modelo") \
               .merge(dim_marca, on="id_marca")

resultado = df.groupby("marca")["valor"].agg(
    maximo=("max"),
    minimo=("min")
).reset_index()

resultado["variacao_valor"] = resultado["maximo"] - resultado["minimo"]
resultado = resultado.rename(columns={
    "maximo": "valor_maximo",
    "minimo": "valor_minimo"
}).sort_values("variacao_valor", ascending=False)

resultado

        marca  valor_maximo  valor_minimo  variacao_valor
8      Toyota     347409.88      27578.35       319831.53
9  VolksWagen     344525.24      26395.12       318130.12
6      Nissan     349020.52      34249.65       314770.87
0   Chevrolet     342560.76      31924.64       310636.12
7     Renault     349484.86      42517.13       306967.73
5        Jeep     335047.31      33258.56       301788.75
1        Fiat     330378.80      30318.83       300059.97
4     Hyundai     341650.14      46771.90       294878.24
3       Honda     321893.04      28417.10       293475.94
2        Ford     314488.89      60851.24       253637.65

In [37]:
# "Quais modelos automáticos custam em média mais do que os manuais — mostrando o câmbio e a média de preço?"
query_5 = pd.read_sql(""" SELECT 
                                dm.cambio,
                                ROUND(AVG(fp.valor)::numeric, 2) AS media_preco 
                          FROM 
                               dim_modelo AS dm 
                          JOIN  fato_preco AS fp  
                          ON dm.id_modelo = fp.id_modelo 
                          GROUP BY dm.cambio""",engine)
print(query_5)

       cambio  media_preco
0  Automatico    188835.80
1      Manual    194056.62

In [54]:
df = fato_preco.merge(dim_modelo, on="id_modelo")\
               .groupby("cambio")["valor"]\
               .mean().reset_index()\
               .rename(columns={"valor":"media_valor"})\
               .sort_values("media_valor",ascending=False)
df

       cambio    media_valor
1      Manual  194056.617524
0  Automatico  188835.804000

In [5]:
# "Quais as 3 marcas com maior número de modelos 4x4 no banco, mostrando a marca e a quantidade de modelos 4x4?"

query_7 = pd.read_sql("""
    SELECT
        COUNT(md.id_modelo) AS quantidade,
        dm.marca,
        md.modelo
    FROM fato_preco AS fp
    JOIN dim_modelo AS md ON fp.id_modelo = md.id_modelo
    JOIN dim_marca  AS dm ON md.id_marca  = dm.id_marca
    WHERE md.modelo = "4x4"
    GROUP BY dm.marca, md.modelo
""", engine)
print(query_7)
# WHERE
#      modelos = 4x4
# GROUP BY
#      marcas,modelos
# HAVING

# ORDER BY

Empty DataFrame
Columns: [quantidade, marca, modelo]
Index: []